# Generated by Django 2.2.2 on 2020-02-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, verbose_name='comment'),
        ),
    ]
