# Generated by Django 2.2.2 on 2020-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0005_auto_20200210_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='comments/%Y/%m/', verbose_name='Image'),
        ),
    ]
